### ISSUE TITLE
Wondering if it does text/numbers to Gcode

### ISSUE THREAD

**Issue by HenneCuppens** [dillonhuff/gpr#4]
Hello,

I have a small question. I'm looking for a program that can run in a commandline that will output gcode from an input from a string (numbers and text). I was wondering if this does that?

**Comment by dillonhuff** [comment]
@HenneCuppens this program can be run from the command line if you'd like, but I'm not sure what you mean by "output gcode from an input".

**Comment by HenneCuppens** [comment]
Thanks for the first part. On the second part let me try to explain.

I want to send a string (of characters a-z and numbers) to a program and get a return of the gcode. I found a program that does this sort-off in python but I rather have a program running in C++ because I want to keep my files in consistant formats. The input string wil come from a text file.

**Comment by dillonhuff** [comment]
If I'm understanding you correctly then yes, this program should be able to do this.
